/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-10-09 17:19:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _401k_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("       <!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("    function calculateNestEgg(){\r\n");
      out.write("        var salary = document.getElementById(\"salary\").value;\r\n");
      out.write("        var contribution = document.getElementById(\"contribution\").value;\r\n");
      out.write("        var age = document.getElementById(\"age\").value;\r\n");
      out.write("        var retireAge = document.getElementById(\"retireAge\").value;\r\n");
      out.write("        var currentBalance = document.getElementById(\"401kBalance\").value;\r\n");
      out.write("        var rate = document.getElementById(\"rateOfReturn\").value;\r\n");
      out.write("        var employerMatchEnd = document.getElementById(\"employerMatch\").value;\r\n");
      out.write("        var employerMatch = document.getElementById(\"employerContribution\").value;\r\n");
      out.write("        \r\n");
      out.write("        var years = retireAge - age;\r\n");
      out.write("        rate = rate/100;\r\n");
      out.write("        employerMatchEnd = employerMatchEnd/100;\r\n");
      out.write("        employerMatch= employerMatch/100;\r\n");
      out.write("        contribution = contribution/100;\r\n");
      out.write("        var totalEmployerMatch;\r\n");
      out.write("        \r\n");
      out.write("        var i;\r\n");
      out.write("        for(i = 0; i< years; i++)\r\n");
      out.write("        {\r\n");
      out.write("            if(contribution >= employerMatchEnd){\r\n");
      out.write("                totalEmployerMatch = employerMatchEnd*salary*employerMatch;\r\n");
      out.write("            }\r\n");
      out.write("            else \r\n");
      out.write("            totalEmployerMatch = contribution * salary * employerMatch;\r\n");
      out.write("       \r\n");
      out.write("          currentBalance =  parseFloat(currentBalance)+ parseFloat(currentBalance * rate) + parseFloat(salary * contribution);\r\n");
      out.write("          \r\n");
      out.write("          currentBalance = currentBalance+totalEmployerMatch;\r\n");
      out.write("          \r\n");
      out.write("          currentBalance = currentBalance.toFixed(2);\r\n");
      out.write("          \r\n");
      out.write("        }//end of loop\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"results\").innerHTML = \"Nest Egg: $\"+ currentBalance;\r\n");
      out.write("        \r\n");
      out.write("    }//end of function\r\n");
      out.write("    </script>\r\n");
      out.write("    <style>\r\n");
      out.write("    body{\r\n");
      out.write("        background-color:black;\r\n");
      out.write("        color:white;\r\n");
      out.write("        font-size:30px;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    h1{\r\n");
      out.write("        background-color:green;\r\n");
      out.write("        text-align:center;\r\n");
      out.write("    }\r\n");
      out.write("    h2{\r\n");
      out.write("        text-align:center;\r\n");
      out.write("    }\r\n");
      out.write("  button{\r\n");
      out.write(" width:25%;\r\n");
      out.write("    height:40px;\r\n");
      out.write("    font-size:20px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    background-color:green;\r\n");
      out.write("    }\r\n");
      out.write("    pre{\r\n");
      out.write("        \r\n");
      out.write("        background-color:black;\r\n");
      out.write("        color:white;\r\n");
      out.write("         display: block;\r\n");
      out.write("    font-family: monospace;\r\n");
      out.write("    white-space: pre;\r\n");
      out.write("    margin: 1em 0;\r\n");
      out.write("    }\r\n");
      out.write(".slider {\r\n");
      out.write("    -webkit-appearance: none;  /* Override default CSS styles */\r\n");
      out.write("    appearance: none;\r\n");
      out.write("    width: 2px; /* Full-width */\r\n");
      out.write("    height: 5px; /* Specified height */\r\n");
      out.write("    background: white; /* Grey background */\r\n");
      out.write("    outline: none; /* Remove outline */\r\n");
      out.write("    opacity: 0.7; /* Set transparency (for mouse-over effects on hover) */\r\n");
      out.write("    -webkit-transition: .2s; /* 0.2 seconds transition on hover */\r\n");
      out.write("    transition: opacity .2s;\r\n");
      out.write("}\r\n");
      out.write(".slidecontainer {\r\n");
      out.write("    width: 55%; /* Width of the outside container */\r\n");
      out.write("}\r\n");
      out.write(".small{\r\n");
      out.write("    font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#results{\r\n");
      out.write("    color:lime;\r\n");
      out.write("}\r\n");
      out.write("#logo{\r\n");
      out.write("    background-color:black;\r\n");
      out.write("}\r\n");
      out.write("#text{\r\n");
      out.write("    width:100%;\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("    color:black;\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    <body>\r\n");
      out.write("    <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"welcome.html\">BudgetBuddy.com</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Budget Tools\r\n");
      out.write("          <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a href=\"quickBudget.html\">Quick Budget</a></li>\r\n");
      out.write("              <li><a href=\"401k.html\">401k Calculator</a></li>\r\n");
      out.write("              <li><a href=\"compoundInterest.html\">Compound Interest Calculator</a></li>\r\n");
      out.write("              </ul></li>\r\n");
      out.write("      \r\n");
      out.write("              \r\n");
      out.write("                <li class=\"active\">\r\n");
      out.write("          <a  href=\"login.html\">Login\r\n");
      out.write("         </a>\r\n");
      out.write("          </li>\r\n");
      out.write("               <li class=\"active\">\r\n");
      out.write("          <a  href=\"signUp.html\">Sign Up\r\n");
      out.write("         </a>\r\n");
      out.write("          </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("         <label>What is your current age?</label><br>\r\n");
      out.write("    <div class=\"slidecontainer\">\r\n");
      out.write("  <input type=\"range\" min=\"15\" max=\"65\" value=\"30\" class=\"slider\" id= \"age\">\r\n");
      out.write("  <p>Current Age: <span id= \"ageOut\"></span></p>\r\n");
      out.write("</div><br>\r\n");
      out.write("<script>\r\n");
      out.write("var slider4 = document.getElementById(\"age\");\r\n");
      out.write("var output4 = document.getElementById(\"ageOut\");\r\n");
      out.write("output4.innerHTML = slider4.value;\r\n");
      out.write("\r\n");
      out.write("slider4.oninput = function() {\r\n");
      out.write("  output4.innerHTML = this.value;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("    <label>What age do you want to retire?</label><br>\r\n");
      out.write("       <div class=\"slidecontainer\">\r\n");
      out.write("  <input type=\"range\" min=\"35\" max=\"90\" value=\"65\" class=\"slider\" id= \"retireAge\">\r\n");
      out.write("  <p>Retirement Age: <span id= \"retireAgeOut\"></span></p>\r\n");
      out.write("</div><br>\r\n");
      out.write("<script>\r\n");
      out.write("var slider5 = document.getElementById(\"retireAge\");\r\n");
      out.write("var output5 = document.getElementById(\"retireAgeOut\");\r\n");
      out.write("output5.innerHTML = slider5.value;\r\n");
      out.write("\r\n");
      out.write("slider5.oninput = function() {\r\n");
      out.write("  output5.innerHTML = this.value;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("    <label>What is your annual salary?</label><br>\r\n");
      out.write("          <div class=\"slidecontainer\">\r\n");
      out.write("  <input type=\"range\" min=\"10000\" max=\"300000\" value=\"35000\" step= \"1000\"class=\"slider\" id= \"salary\">\r\n");
      out.write("  <p>Current Annual Salary: $ <span id= \"salaryOut\"></span></p>\r\n");
      out.write("</div><br>\r\n");
      out.write("<script>\r\n");
      out.write("var slider6 = document.getElementById(\"salary\");\r\n");
      out.write("var output6 = document.getElementById(\"salaryOut\");\r\n");
      out.write("output6.innerHTML = slider6.value;\r\n");
      out.write("\r\n");
      out.write("slider6.oninput = function() {\r\n");
      out.write("  output6.innerHTML = this.value;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("    <label>What is the current balance in your 401k account?</label><br>\r\n");
      out.write("             <div class=\"slidecontainer\">\r\n");
      out.write("  <input type=\"range\" min=\"0\" max=\"500000\" value=\"1000\" step=\"500\" class=\"slider\" id= \"401kBalance\">\r\n");
      out.write("  <p>Current 401k balance: $ <span id= \"401kBalanceOut\"></span></p>\r\n");
      out.write("</div><br>\r\n");
      out.write("<script>\r\n");
      out.write("var slider7 = document.getElementById(\"401kBalance\");\r\n");
      out.write("var output7 = document.getElementById(\"401kBalanceOut\");\r\n");
      out.write("output7.innerHTML = slider7.value;\r\n");
      out.write("\r\n");
      out.write("slider7.oninput = function() {\r\n");
      out.write("  output7.innerHTML = this.value;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("     <label>What is the average rate of return that you expect? </label><br>\r\n");
      out.write(" <div class=\"slidecontainer\">\r\n");
      out.write("  <input type=\"range\" min=\"1\" max=\"15\" value=\"5\" step=\".5\" class=\"slider\" id=\"rateOfReturn\">\r\n");
      out.write("  <p>Rate of Return: <span id=\"sliderOutput\"></span>%</p>\r\n");
      out.write("</div><br>\r\n");
      out.write("<script>\r\n");
      out.write("var slider = document.getElementById(\"rateOfReturn\");\r\n");
      out.write("var output = document.getElementById(\"sliderOutput\");\r\n");
      out.write("output.innerHTML = slider.value;\r\n");
      out.write("\r\n");
      out.write("slider.oninput = function() {\r\n");
      out.write("  output.innerHTML = this.value;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    <label>What is the percent of your paycheck that you contribute annually? </label><br>\r\n");
      out.write("    <div class=\"slidecontainer\">\r\n");
      out.write("  <input type=\"range\" min=\"1\" max=\"100\" value=\"3\" class=\"slider\" id=\"contribution\">\r\n");
      out.write("  <p>Contribution: <span id=\"contributionOutput\"></span>%</p>\r\n");
      out.write("</div><br>\r\n");
      out.write("<script>\r\n");
      out.write("var slider1 = document.getElementById(\"contribution\");\r\n");
      out.write("var output1 = document.getElementById(\"contributionOutput\");\r\n");
      out.write("output1.innerHTML = slider1.value;\r\n");
      out.write("\r\n");
      out.write("slider1.oninput = function() {\r\n");
      out.write("  output1.innerHTML = this.value;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("       \r\n");
      out.write("    <label>When does your employer match end?</label> <div class=\"small\"></div><br>\r\n");
      out.write("    <div class=\"slidecontainer\">\r\n");
      out.write("  <input type=\"range\" min=\"1\" max=\"100\" value=\"6\" class=\"slider\" id=\"employerMatch\">\r\n");
      out.write("  <p>Employer Match Ends: <span id=\"employerMatchOutput\"></span>%</p>\r\n");
      out.write("</div><br>\r\n");
      out.write("<script>\r\n");
      out.write("var slider2 = document.getElementById(\"employerMatch\");\r\n");
      out.write("var output2 = document.getElementById(\"employerMatchOutput\");\r\n");
      out.write("output2.innerHTML = slider2.value;\r\n");
      out.write("\r\n");
      out.write("slider2.oninput = function() {\r\n");
      out.write("  output2.innerHTML = this.value;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("             \r\n");
      out.write("    <label>How much of your contribution does your employer match? </label><br>\r\n");
      out.write("     <div class=\"slidecontainer\">\r\n");
      out.write("  <input type=\"range\" min=\"1\" max=\"100\" value=\"50\" class=\"slider\" id=\"employerContribution\">\r\n");
      out.write("  <p>Employer Match: <span id=\"employerContributionOutput\"></span>%</p>\r\n");
      out.write("</div><br>\r\n");
      out.write("<script>\r\n");
      out.write("var slider3 = document.getElementById(\"employerContribution\");\r\n");
      out.write("var output3 = document.getElementById(\"employerContributionOutput\");\r\n");
      out.write("output3.innerHTML = slider3.value;\r\n");
      out.write("\r\n");
      out.write("slider3.oninput = function() {\r\n");
      out.write("  output3.innerHTML = this.value;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"results\">\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    <button onclick=\"calculateNestEgg()\" type=\"button\" >Calculate Nest Egg</button>\r\n");
      out.write("    <div id=\"results\">\r\n");
      out.write("        </div><br><br>\r\n");
      out.write("\r\n");
      out.write("        </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
