/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-10-09 17:19:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class quickBudget_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<!--calculate using budget template based on %55 for necessities, %30 rent/mortgage, %10 savings, %10 retirement, %10 education, \r\n");
      out.write("       %10 fun account, and %5 for donations. calculate using the input from the annual income text field -->\r\n");
      out.write("              <!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function calculateBudget(){\r\n");
      out.write("income = document.getElementById(\"monthlyIncome\").value;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"rent\").innerHTML = \"$\"+ income * .3;\r\n");
      out.write("document.getElementById(\"retirement\").innerHTML = \"$\"+ income * .1;\r\n");
      out.write("document.getElementById(\"otherBills\").innerHTML = \"$\"+ income * .25;\r\n");
      out.write("document.getElementById(\"savings\").innerHTML = \"$\"+ income * .1;\r\n");
      out.write("document.getElementById(\"fun\").innerHTML = \"$\"+ income * .1;\r\n");
      out.write("document.getElementById(\"donations\").innerHTML = \"$\"+ income * .05;\r\n");
      out.write("document.getElementById(\"education\").innerHTML = \"$\"+ income * .1;\r\n");
      out.write("\r\n");
      out.write("}//end of calculateBudget Function\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("background-color:black;\r\n");
      out.write("color:white;\r\n");
      out.write("font-size:30px;\r\n");
      out.write("}\r\n");
      out.write("form{\r\n");
      out.write("display:grid;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#form2 input{\r\n");
      out.write("color:lime;\r\n");
      out.write("background-color:black;\r\n");
      out.write("}\r\n");
      out.write("#logo{\r\n");
      out.write("    background-color:black;\r\n");
      out.write("}\r\n");
      out.write("p{\r\n");
      out.write("    color:lime;\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("    width:25%;\r\n");
      out.write("    color:black;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("    width:25%;\r\n");
      out.write("    height:40px;\r\n");
      out.write("    font-size:20px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    background-color:green;\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("    background-color:green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("                  <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"welcome.html\">BudgetBuddy.com</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Budget Tools\r\n");
      out.write("          <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a href=\"quickBudget.html\">Quick Budget</a></li>\r\n");
      out.write("              <li><a href=\"401k.html\">401k Calculator</a></li>\r\n");
      out.write("              <li><a href=\"compoundInterest.html\">Compound Interest Calculator</a></li>\r\n");
      out.write("              </ul></li>\r\n");
      out.write("      \r\n");
      out.write("              \r\n");
      out.write("                <li class=\"active\">\r\n");
      out.write("          <a  href=\"login.html\">Login\r\n");
      out.write("         </a>\r\n");
      out.write("          </li>\r\n");
      out.write("               <li class=\"active\">\r\n");
      out.write("          <a  href=\"signUp.html\">Sign Up\r\n");
      out.write("         </a>\r\n");
      out.write("          </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <h1>Create a Budget</h1>\r\n");
      out.write("<label>What is your monthly gross income? </label><br>\r\n");
      out.write("<input type=\"number\" id=\"monthlyIncome\"><br>\r\n");
      out.write("<button onclick=\"calculateBudget()\">Calculate Budget</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p id=\"rentp\"> </p>\r\n");
      out.write("\r\n");
      out.write("<form name=\"form2\">\r\n");
      out.write("<label>Monthly Budget for Rent/Mortgage </label>\r\n");
      out.write("<p  id=\"rent\"></p>\r\n");
      out.write("<label>Monthly Budget for Savings</label>\r\n");
      out.write("<p  id=\"savings\"></p>\r\n");
      out.write("<label>Monthly Budget for Retirement Accounts </label>\r\n");
      out.write("<p  id=\"retirement\"></p>\r\n");
      out.write("<label>Monthly Budget for Other Bills (Car, Insurance, Utilities, Healthcare, etc.)</label>\r\n");
      out.write("<p  id=\"otherBills\"></p>\r\n");
      out.write("<label>Monthly Budget for Education </label>\r\n");
      out.write("<p  id=\"education\"></p>\r\n");
      out.write("<label>Monthly Budget for Donations </label>\r\n");
      out.write("<p  id=\"donations\"></p>\r\n");
      out.write("<label>Monthly Budget for Entertainment (Restaraunts,Movies,Bars,Bowling, etc.)</label>\r\n");
      out.write("<p  id=\"fun\"></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
