/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-10-09 18:42:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/Josh/Desktop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/budgetbuddy/WEB-INF/lib/spring-webmvc-4.3.0.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1465565808000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1539021125129L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.0.RELEASE.jar", Long.valueOf(1539056887278L));
    _jspx_dependants.put("jar:file:/C:/Users/Josh/Desktop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/budgetbuddy/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("jar:file:/C:/Users/Josh/Desktop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/budgetbuddy/WEB-INF/lib/spring-webmvc-4.3.0.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1465565808000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#section{\r\n");
      out.write("background-color:black;\r\n");
      out.write("}\r\n");
      out.write("#jumbo{\r\n");
      out.write("background-color:green;\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("text-align:center;}\r\n");
      out.write("\r\n");
      out.write("#head1{\r\n");
      out.write("background-color:green;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("#body{\r\n");
      out.write("background-color:black;\r\n");
      out.write("}\r\n");
      out.write("head{\r\n");
      out.write("background-color:green;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("#panelBody{\r\n");
      out.write("background-color:black;}\r\n");
      out.write("#bottom{\r\n");
      out.write("background-color:black;}\r\n");
      out.write("#loginButton{\r\n");
      out.write("background-color:green;}\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css\">\r\n");
      out.write("<title>Budget Buddy Login</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body\">\r\n");
      out.write(" <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"welcome.html\">BudgetBuddy.com</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Budget Tools\r\n");
      out.write("          <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a href=\"quickBudget.html\">Quick Budget</a></li>\r\n");
      out.write("              <li><a href=\"401k.html\">401k Calculator</a></li>\r\n");
      out.write("              <li><a href=\"compoundInterest.html\">Compound Interest Calculator</a></li>\r\n");
      out.write("              </ul></li>\r\n");
      out.write("      \r\n");
      out.write("              \r\n");
      out.write("                <li class=\"active\">\r\n");
      out.write("          <a  href=\"login.html\">Login\r\n");
      out.write("         </a>\r\n");
      out.write("          </li>\r\n");
      out.write("               <li class=\"active\">\r\n");
      out.write("          <a  href=\"signup.html\">Sign Up\r\n");
      out.write("         </a>\r\n");
      out.write("          </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("   <section>\r\n");
      out.write("      <div id=\"jumbo\"class=\"jumbotron\">\r\n");
      out.write("         <div id=\"head1\"class=\"container\">\r\n");
      out.write("            <h1><img src=\"resources/images/budget buddy logo.PNG\"></h1>\r\n");
      out.write("            \r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </section>\r\n");
      out.write("   <div id=\"bottom\"class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("         <div class=\"col-md-4 col-md-offset-4\">\r\n");
      out.write("            <div class=\"panel panel-default\">\r\n");
      out.write("               <div class=\"panel-heading\">\r\n");
      out.write("                  <h3 class=\"panel-title\">Create New Account</h3>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div id=\"panelBody\" class=\"panel-body\">\r\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"post\" class=\"form-horizontal\">\r\n");
      out.write("                     \r\n");
      out.write("                  \r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"input-group input-sm\">\r\n");
      out.write("                        <label class=\"input-group-addon\" for=\"username\"><i\r\n");
      out.write("                           class=\"fa fa-user\"></i></label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("                           id=\"userId\" name=\"userId\" placeholder=\"Enter First Name\"\r\n");
      out.write("                           required>\r\n");
      out.write("                     </div>\r\n");
      out.write("                      <div class=\"input-group input-sm\">\r\n");
      out.write("                        <label class=\"input-group-addon\" for=\"username\"><i\r\n");
      out.write("                           class=\"fa fa-user\"></i></label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("                           id=\"userId\" name=\"userId\" placeholder=\"Enter Last Name\"\r\n");
      out.write("                           required>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"input-group input-sm\">\r\n");
      out.write("                        <label class=\"input-group-addon\" for=\"username\"><i\r\n");
      out.write("                           class=\"fa fa-user\"></i></label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("                           id=\"userId\" name=\"userId\" placeholder=\"Enter Email Address\"\r\n");
      out.write("                           required>\r\n");
      out.write("                     </div>\r\n");
      out.write("                      <div class=\"input-group input-sm\">\r\n");
      out.write("                        <label class=\"input-group-addon\" for=\"username\"><i\r\n");
      out.write("                           class=\"fa fa-user\"></i></label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("                           id=\"userId\" name=\"userId\" placeholder=\"Enter Birthday\"\r\n");
      out.write("                           required>\r\n");
      out.write("                     </div>\r\n");
      out.write("                      <div class=\"input-group input-sm\">\r\n");
      out.write("                        <label class=\"input-group-addon\" for=\"username\"><i\r\n");
      out.write("                           class=\"fa fa-user\"></i></label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("                           id=\"userId\" name=\"userId\" placeholder=\"Enter Username\"\r\n");
      out.write("                           required>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"input-group input-sm\">\r\n");
      out.write("                        <label class=\"input-group-addon\" for=\"password\"><i\r\n");
      out.write("                           class=\"fa fa-lock\"></i></label> <input type=\"password\"\r\n");
      out.write("                           class=\"form-control\" id=\"password\" name=\"password\"\r\n");
      out.write("                           placeholder=\"Enter Password\" required>\r\n");
      out.write("                     </div>\r\n");
      out.write("                       <div class=\"input-group input-sm\">\r\n");
      out.write("                        <label class=\"input-group-addon\" for=\"password\"><i\r\n");
      out.write("                           class=\"fa fa-lock\"></i></label> <input type=\"password\"\r\n");
      out.write("                           class=\"form-control\" id=\"password\" name=\"password\"\r\n");
      out.write("                           placeholder=\"Confirm Password\" required>\r\n");
      out.write("                     </div>\r\n");
      out.write("\r\n");
      out.write("                     <div class=\"form-actions\">\r\n");
      out.write("                        <input type=\"submit\"\r\n");
      out.write("                           id=\"loginButton\"class=\"btn btn-block btn-primary btn-default\" value=\"Log in\">\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/signUp.jsp(86,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("loginUrl");
      // /WEB-INF/jsp/signUp.jsp(86,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/login");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
